### ISSUE TITLE
Build stage fails to patch the BuildConfig

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#120]
During `stageStartOpenshiftBuild`, the following error might happen:
```
Error from server: jsonpatch replace operation does not apply: doc is missing key: /spec/output/imageLabels
```

This happens when the existing `BuildConfig` does not have the path `/spec/output/imageLabels`. As a workaround, it is possible to manually add it (potentially one needs to add a dummy value) like so:
```
...
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    imageLabels:
    - name: foo
      value: bar
    to:
      kind: ImageStreamTag
...
```

Ideally the stage should check if the path exists and create the path if it does not exist yet.

FYI @m-apsolon @gerardcl
