### ISSUE TITLE
Using base image from other namespace did not work 

### ISSUE THREAD

**Issue by henrjk** [opendevstack/ods-jenkins-shared-library#179]
**Describe the bug**
I experimented with using a base image created in openshift and then referencing this in the buildConfig as follows:

```yaml
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
...
  spec:
     strategy:
       dockerStrategy:
         from:
           kind: ImageStreamTag
           name: 'be-python-flask-base:${BASE_TAG}'
          namespace: example-cd
       type: Docker
``` 

However during the shared library `buildArgs` patch created in https://github.com/opendevstack/ods-jenkins-shared-library/blob/a7ff00a69518c447829aa00741cdd8d849bb9c8e/vars/stageStartOpenshiftBuild.groovy#L106 replaces the entire `dockerStrategy` and this removes the `from` information.

As a consequence the image was attempted to be loaded from the docker registry instead of the internal registry which failed. 

I'd be happy to work on a fix unless there was some known reason that a more targeted patch would not work. 

**To Reproduce**
I don't have something I can share ready. Please ask if clarification is needed. 

**Expected behavior**
The patch should only add build args and leave other pieces of the dockerStrategy alone. 

**Affected version (please complete the following information):**
 - OpenShift:3.11
 - OpenDevStack master
