### ISSUE TITLE
Release Manager cannot find param in .env files in ODS 3.x

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-jenkins-shared-library#473]
**Describe the bug**
We have quite a few users that have reported the following unexpected behaviour when deploying their component to QA using Release Manager in ODS 3.x.

Given a component that requires a new parameter in the `template.yaml`, for instance `SAML_SETTINGS_PATH`:

```
apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  ...
  spec:
    replicas: 1
    ...
      spec:
        containers:
        - env:
          - name: SAML_SETTINGS_PATH
            value: ${SAML_SETTINGS_PATH}
...

parameters:
...

- name: SAML_SETTINGS_PATH
  required: true
```

**To Reproduce**
1. Create an app component through the Provisoning App.
2. Create the Release Manager component through the Provisioning App.
3. Configure Release Manager to deploy the app component in the metadata.yml.
4. Create 3 files in the repository of the Release Manager, `dev.env`, `qa.env` and `prod.env` in the `release/ods-generated-${version}` branch and set any value to `SAML_SETTINGS_PATH`. 
5. In Jenkins, go to the MRO pipeline and deploy a new release version first to DEV, then to QA.

**Expected behavior**
The deployment of the new version to QA using Release Manager should be able to find the parameter `SAML_SETTINGS_PATH` in the corresponding `qa.env` file defined in the Release Manager repository. However, the error described further below occurs.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.x

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
+ tailor --non-interactive -n ****-test apply --selector app=***** --param ODS_OPENSHIFT_APP_DOMAIN=****** --preserve bc:/spec/output/imageLabels --preserve bc:/spec/output/to/name --ignore-unknown-parameters bc,is
error: unable to process template
  Required value: template.parameters[2]: parameter SAML_SETTINGS_PATH is required and must be specified
Comparing templates in . with OCP namespace ***-test.
Limiting resources to bc,is with selector app=****.
Could not process template.yml template: exit status 1
```

**Additional context**

Release Manager is not able to find the param `SAML_SETTINGS_PATH` from the file `qa.env` in the Release Manager repository:

### Component: release-manager
```
Branch: release/ods-generated-1
Files: ./dev.env
	 ./qa.env
	 ./prod.env
```

However, if the param `SAML_SETTINGS_PATH` is **also** specified in the app component in the file `./openshift/{project-key}-qa.env`, Release Manager is able to find the param and the deployment is carried out successfully.

### Component: my-app
```
Branch: release/ods-generated-1
Files: ./openshift/{project-key}-dev.env
	 ./openshift/{project-key}-qa.env
	 ./openshift/{project-key}-prod.env
```

In conclusion, the `SAML_SETTINGS_PATH`  param needs to exist in **both** locations and it is annoning for the users to keep the values of these files in sync.

⚠ *P.S: Note that, to make matters worse, in the app component the naming convention of the `.env` files is different compared to the naming used in the Release Manager component.*
