### ISSUE TITLE
latest master - release mgr image verification fails because of *-cd image refactoring

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#547]
```
WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label[0m
[0;32m    amazon-ebs: + oc -n unitt-dev get DeploymentConfig -l app=unitt-golang -o 'template={{range .items}}{{.kind}}:{{.metadata.name}} {{end}}'[0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: DEBUG: ODS created deployments for golang: [golang], all deployments: [golang][0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: WARN: ! Image out of scope! Deployment: golang / Container: golang / Owner: unitt-cd[0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: Offending: [Deployment: golang / Container: golang / Owner: unitt-cd][0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: Failed in branch golang[0m
[0;32m    amazon-ebs: [Pipeline] // parallel[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // node[0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: Offending: [Deployment: golang / Container: golang / Owner: unitt-cd][0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: [Finalize] **** ENDED orchestration stage **** (took 4372 ms)[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // stage[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // withEnv[0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: [ods-mro-pipeline] **** ENDED orchestration pipeline **** (took 180128 ms)[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // podTemplate[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // node[0m
[0;32m    amazon-ebs: [Pipeline] End of Pipeline[0m
[0;32m    amazon-ebs: Offending: [Deployment: golang / Container: golang / Owner: unitt-cd][0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.phases.FinalizeOdsComponent.verifyDeploymentsBuiltByODS(FinalizeOdsComponent.groovy:170)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.phases.FinalizeOdsComponent.run(FinalizeOdsComponent.groovy:38)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:323)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:153)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:309)[0m
[0;32m    amazon-ebs: 	at ___cps.transform___(Native Method)[0m
```

hurray ... :) 

based on teststeps in https://github.com/opendevstack/ods-quickstarters/blob/master/release-manager/testdata/steps.yml

**Comment by michaelsauter** [comment]
Looking into this.

**Comment by michaelsauter** [comment]
Ok, I found what's causing the issue

`Pod` resource `spec` has (same as the `DeploymentConfig` resource):
```
spec:
  containers:
    - image: >-
        172.30.21.196:5000/unitt-dev/golang@sha256:91f8ad433bf80d4c5f439cdfa7f77ca99f356cb979f29155409e73cf0f1e471d
```
... but it's `status` has:
```
status:
  containerStatuses:
    - containerID: >-
        docker://59c21b895c27aa081bc600497bc7c327afb34250c7f34b2cc4e4dd84c7960f11
      image: '172.30.21.196:5000/unitt-cd/golang:ce3182fb'
      imageID: >-
        docker-pullable://172.30.21.196:5000/unitt-cd/golang@sha256:91f8ad433bf80d4c5f439cdfa7f77ca99f356cb979f29155409e73cf0f1e471d
```

We use the `status` information to fill the pod data.
