### ISSUE TITLE
Use of metadata.yml: repositories.id collides with handling of unit tests

### ISSUE THREAD

**Issue by serverhorror** [opendevstack/ods-jenkins-shared-library#563]
**Describe the bug**
When this occurs `release-manager` complains about not being able to unstash test results despite sucessfully saving test results earlier.

It is a very confusing order of messages and presentation of errors.

**To Reproduce**
1. create a component
2. create a release-manager component
3. in release-manager metadata.yml

  ```
  id: example-project
    name: Project Example Project
    description: Description of Example Project.

    services:
    bitbucket:
        credentials:
        id: example-cd-cd-user-with-password
    nexus:
        repository:
        name: leva-documentation

    repositories:
    #######################################################
    # Problem is here id is prefixed with the project name#
    # If you change id to 'components' the build passes   #
    #######################################################
    - id: example-components
        name: odm-components
        branch: master
        type: ods
    allowPartialRebuild: true

    environments:
    dev:
      apiUrl: https://dev.example.com
      credentialsId: cd-user
    qa:
      apiUrl: https://qa.example.com
      credentialsId: example-cd-example-qa
    prod:
        apiUrl: https://prod.example.com
        credentialsId: example-cd-example-prod
  ```

**Expected behavior**
Consistent usage of naming/ids or any kind of identifier when saving and receiving test results.

I believe the relevant code lines are here:

* https://github.com/opendevstack/ods-jenkins-shared-library/blob/3.x/src/org/ods/component/Pipeline.groovy#L259-L261
* https://github.com/opendevstack/ods-jenkins-shared-library/blob/3.x/src/org/ods/orchestration/Stage.groovy#L99-L102

**Screenshots**

![grafik](https://user-images.githubusercontent.com/36151/105349319-d260d100-5be9-11eb-84c6-c2b0fba2edf2.png)

![grafik](https://user-images.githubusercontent.com/36151/105349371-e60c3780-5be9-11eb-8ffe-cc46ef5e77d2.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.x (`refs/heads/3.x revision f579b9f0419d154f8a6ed8fd13be1bbea55bae29`)
