### ISSUE TITLE
[feat]: customize git properties of release manager

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-jenkins-shared-library#594]
**Is your feature request related to a problem? Please describe.**
It would be great if some git properties could be customized for the release manager, like the commit message. This would also fix the following bug with a simple edit (#593). Instead you have to wait until the next release/hotfix.

**Describe the solution you'd like**
Customization of Git properties via env variables or a configuration file

```sh
GIT_AUTHOR_NAME=The Releaser
GIT_AUTHOR_MAIL=release@example.com
```
or
```yml
# metadata.yml
id: foo
name: Foo

configuration:
  git:
    author: 
      mail: release@example.com
      name: The Releaser
    commit: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
```

**Describe alternatives you've considered**
-

**Additional context**
Reference as I see it somehow: https://github.com/semantic-release/git#configuration
