### ISSUE TITLE
How code libraries are being handled with Release Manager?

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-jenkins-shared-library#603]
**Is your feature request related to a problem? Please describe.**
We have a use case where two components need to use a Python library.

- `Component A` - Dockerplain quickstarter.
The Jenkinsfile will build, test and deploy the component to OpenShift.

- `Component B` - Dockerplain quickstarter.
The Jenkinsfile will build, test and deploy the component to OpenShift.

- `Library` - Python quickstarter.
The Jenkinsfile will package and upload the library to Nexus (it will not be deployed to OpenShift using `odsComponentStageRolloutOpenShiftDeployment()` because of the own nature of the component).

It would look like this:

`Component A` --- uses ---> `Library` 
`Component B` --- uses ---------^

![image](https://user-images.githubusercontent.com/15997951/110930279-328e0c80-8329-11eb-8b12-ab62fc5bd42d.png)

And the Release Manager is configured as follows:

```yaml
repositories: 
  - id: ComponentA
    type: ods
  - id: ComponentB
    type: ods
  - id: Library
    type: ods-service
```

When deploying to D using Release Manager, we get the following error:

```
java.lang.RuntimeException: DeploymentConfigs (component: 'Library') found that are not ODS managed: '[Library]'!
Please fix by rolling them out through 'odsComponentStageRolloutOpenShiftDeployment()'!
```
And that's expected - the Library component is a Python library (not an app that needs to run in OpenShift as a container).
So we have removed the DeploymentConfig from the Tailor template file, leaving it practically empty (no objects defined):

```yaml
apiVersion: template.openshift.io/v1
kind: Template
objects:
parameters:
- name: TAILOR_NAMESPACE
  required: true
- name: ODS_OPENSHIFT_APP_DOMAIN
  required: true
```

**Describe the solution you'd like**
I'd like to learn more about your opinion on how ODS could easily cover the use case aforementioned. Would it make sense to create a "Library quickstarter" whose Jenkinsfile only takes care of uploading the lib to Nexus, and won't include the `odsComponentStageRolloutOpenShiftDeployment()` stage?

**Describe alternatives you've considered**
So far, the workaround I know to deploy a Python Library in ODS is neither easy nor straightforward to the end-user:

1. Create a Python quickstarter.
2. Edit the Jenkinsfile to compress the package, upload it to Nexus and comment out the deployment stage:
```
    stageCompressPythonLibrary(context)
    odsComponentStageUploadToNexus(context, [repository: 'candidates'])
    // odsComponentStageRolloutOpenShiftDeployment()
```
3. Make a first deployment with Release Manager (it will fail)
4. Rename the `openshift-exported` folder to `openshift` and empty the `openshift/template.yml` file:
```yaml
apiVersion: template.openshift.io/v1
kind: Template
objects:
parameters:
- name: TAILOR_NAMESPACE
  required: true
- name: ODS_OPENSHIFT_APP_DOMAIN
  required: true
```
5. Remove the OpenShift resources (DeploymentConfig, Service, Routes, etc) that were created by the first deployment. If you don't do this step, you will get the following exception when deploying to D:

```
java.lang.RuntimeException: DeploymentConfigs (component: 'interfacepackage') found that are not ODS managed: '[interfacepackage]'!
Please fix by rolling them out through 'odsComponentStageRolloutOpenShiftDeployment()'!
```

If you've reached this point, thank you for your time reading this😀

ping @michaelsauter @metmajer
