### ISSUE TITLE
jenkins slave still does not run with jenkins SA on latest master

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#78]
from the logs
```
[@containerTemplate(name=jnlp,image=docker-registry.default.svc:5000/cd/jenkins-slave-base,workingDir=/tmp,alwaysPullImage=true,args=${computer.jnlpmac} ${computer.name},*serviceAccount=jenkins*)], 

‘Jenkins’ doesn’t have label ‘pod-a3baadd4-edd5-4b7b-8238-ebadc8eda50d’
Agent jenkins-slave-xklpg-x6dk3 is provisioned from template Kubernetes Pod Template
Agent specification [Kubernetes Pod Template] (pod-a3baadd4-edd5-4b7b-8238-ebadc8eda50d): 
* [jnlp] docker-registry.default.svc:5000/cd/jenkins-slave-base

Running on jenkins-slave-xklpg-x6dk3 in /tmp/workspace/ods26-cd/ods26-cd-dockerplain-master
``` 

```
[ods26-cd-dockerplain-master] Running shell script
+ oc whoami
system:serviceaccount:ods26-cd:default
```

**Comment by clemensutschig** [comment]
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/OdsPipeline.groovy#L50-L54

does not look like it would take the SA into account. this breaks current master (and me from pushing this to production(

**Comment by clemensutschig** [comment]
this should have been fixed with #70

**Comment by clemensutschig** [comment]
I took a look into the pod def of the spun up pod 
``` 
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1002070000
    seLinuxOptions:
      level: 's0:c46,c0'
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
``` 

so clearly this thing does NOT run as jenkins
